name: export-docker-container
on: 
  push:
    branches: [ GithubActions ]
  pull_request:
    branches: [ GithubActions ]

jobs:
  job-name:
    runs-on: ubuntu-latest
    services:
      testing-service:
        image: hoeleboele:docker-image
        ports:
           - 3001:3000
