name: DockerExport
on: 
  push:
    branches: [ GithubActions ]
  pull_request:
    branches: [ GithubActions ]
  
  workflow_dispatch:
  
docker-login:
- uses: https://hub.docker.com/
- with: https://hub.docker.com/
    login-server:
    username: ${{DOCKERHUB_USERNAME}}
    password: ${{DOCKER_PASSWORD}}

jobs:
  export-docker-image:
    runs-on: ubuntu-latest
    services:
      testing-service:
        image: hoeleboele:docker-image
        ports:
           - 3001:3000

    steps:
      - name: Get from service-1
        run: docker push hoeleboele/docker-image
